---

# Main tasks file for base-packages role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::base-packages'
    - 'role::base-packages::init'
    - 'role::base-packages::install'


- name: 'INSTALL | OS families install tasks'
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  become: True
  tags:
    - 'role::base-packages'
    - 'role::base-packages::install'
